version: "3"
services:
  app:
    image: jae518/cicd-aws:latest
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - redis
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - redis